### ISSUE TITLE
Hospital Discharge Data, Sep 2013 through Aug 2014

### ISSUE THREAD

**Issue by robparal** [smartchicago/chicago-atlas#222]
Below are links to files on all 1) inpatient, 2) outpatient and 3) outpatient injury-related admissions to hospitals and ambulatory surgical centers of persons residing in Chicago zip codes. This represents a second year of data of the discharge data currently (as of July 2015) posted to Chicago Health Atlas.

Data cells represented by a \* have been suppressed per requirements of the Illinois Dept. of Public Health. 

Most of the data are available by race/Latino categories, though I am not including these in the links below because such information was not used last year.

https://drive.google.com/file/d/0B9vdVdII0XSCU0l3b0FmWFQyS2M/view?usp=sharing
https://drive.google.com/file/d/0B9vdVdII0XSCYkVyVElCVmpidEU/view?usp=sharing
https://drive.google.com/file/d/0B9vdVdII0XSCRzE2U2ZPQW5ORWs/view?usp=sharing

**Comment by marks** [comment]
Just thinking out loud... should this data get onto data.cityofchicago.org to make sure the integrity/chain of command is documented, hopefully kept up to date, and API enabled so data is not floating around on Github.

_I work for Socrata who partners with the City on data.cityofchicago.org if there is anything I can do to connect you and the data owners with the right people._

Mark
mark.silvererg@socrata.com

**Comment by wesleycoates** [comment]
Mark, great comment.  The Illinois Department of Public Health actually owns
the dataset.  I¹m not sure if this particular one could be published on
data.illinois.gov due to privacy concerns, but certainly other datasets of
healthcare facility licensure and certification status could and should be
published.  For instance, when I was at IDPH, we received many requests for
up-to-date long term care facility lists.  While seemingly basic, this was
typically run through an old database and a PDF report was provided to the
requestor.  I published a machine-readable dataset
<https://data.illinois.gov/Public-Health/IDPH-Skilled-Nursing-Facilities-Nur
sing-Homes-/jaeu-5c56> , but it hasn¹t been updated in a couple of years.

Much data about the outcomes
<https://ltc.dph.illinois.gov/webapp/LTCApp/federalsurvey.jsp?facilityid=600
0012>  of inspections are also available
<https://ltc.dph.illinois.gov/webapp/LTCApp/listing.jsp?facilityid=6000012>
, but not machine-readable.  Since Stephen Konya left I¹m not sure who the
open data champion at IDPH is.  Interestingly, this type of information is
frequently requested through FOIA, which tends to be a nice catalyst for
publishing open data.
Matt

From:  Mark Silverberg <notifications@github.com>
Reply-To:  smartchicago/chicago-atlas
<reply+00646044cf17af5a87fd87da67726c9f5e8bab6e8e2d792192cf0000000111be9dd39
2a169ce05a679b1@reply.github.com>
Date:  Wednesday, July 15, 2015 at 5:16 PM
To:  smartchicago/chicago-atlas <chicago-atlas@noreply.github.com>
Subject:  Re: [chicago-atlas] Hospital Discharge Data, Sep 2013 through Aug
2014 (#222)


Just thinking out loud... should this data get onto data.cityofchicago.org
to make sure the integrity/chain of command is documented, hopefully kept up
to date, and API enabled so data is not floating around on Github.

I work for Socrata who partners with the City on data.cityofchicago.org if
there is anything I can do to connect you and the data owners with the right
people.

Mark
mark.silvererg@socrata.com


Reply to this email directly or view it on GitHub
<https://github.com/smartchicago/chicago-atlas/issues/222#issuecomment-12176
5558> .

**Comment by robparal** [comment]
Hi Mark: The data is indeed from the state Dept. of Public Health.  It is
sourced to a specific data request we made, though it is public as such at
this point.

Rob Paral

On Wed, Jul 15, 2015 at 5:16 PM, Mark Silverberg <notifications@github.com>
wrote:

> Just thinking out loud... should this data get onto data.cityofchicago.org
> to make sure the integrity/chain of command is documented, hopefully kept
> up to date, and API enabled so data is not floating around on Github.
>
> *I work for Socrata who partners with the City on data.cityofchicago.org
> <http://data.cityofchicago.org> if there is anything I can do to connect
> you and the data owners with the right people.*
>
> Mark
> mark.silvererg@socrata.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartchicago/chicago-atlas/issues/222#issuecomment-121765558>
> .
>



-- 
Rob Paral
773-609-4510
www.robparal.com
robparal.blogspot.com
<http://www.linkedin.com/in/robparal>

**Comment by marks** [comment]
@wesleycoates & @robparal - thank you for that information. I will work to see if I can connect some dots as I strongly believe it would be better for citizens and government to have the data on the portal and continuously updated.

If anyone who happens upon this thread agrees or knows who the right person at the IL DPH is, please feel free to contact me directly.

**Comment by danxoneil** [comment]
Hi, Mark. I appreciate your comments here.

Smart Chicago Collaborative works very closely with the City of Chicago on matters regarding open data, and no one feels more strongly about this issue than we do.  Here's a [couple years of posts on the matter](http://www.smartchicagocollaborative.org/?s=data+portal).

We work directly with Tom Schenk and others at the City who maintain their data portal. Josh Kalov, who helps maintain Cook County's open data, does so as a [consultant to Smart Chicago](http://www.smartchicagocollaborative.org/people/consultants/current-consultants/josh-kalov/).

Since this data does not come from and is not maintained by the City of Chicago, it would be highly irregular for the data to be stored on the City's portal. The [State of Illinois is also a client of Socrata](https://data.illinois.gov/)— my suggestion is that you start there. Smart Chicago has done a significant amount of work with Illinois as well— see our [Illinois Open Technology Challenge website](http://illinoisopentech.org/) for more. 

There has been a change in leadership at the State level recently— it would be extraordinarily helpful if you engaged with them directly on this matter.

**Comment by KylaWilliams** [comment]
@theandrewbriggs Next data set upload.
