### ISSUE TITLE
Location (by zip) Missing Admissions Explanation 

### ISSUE THREAD

**Issue by theandrewbriggs** [smartchicago/chicago-atlas#230]
Broken off from #225.

Under 'Hospital Admissions' Header, replace '[explanation of inpatient vs outpatient]' with copy explaining the difference (or a link to an explanation).

**Comment by robparal** [comment]
"An outpatient (or out-patient) is a patient who is not hospitalized for 24 hours or more but who visits a hospital, clinic, or associated facility for diagnosis or treatment."

"An inpatient (or in-patient), on the other hand, is "admitted" to the hospital and stays overnight or for an indeterminate time."

from Wikipedia: https://en.wikipedia.org/wiki/Patient#Outpatients_and_inpatients

**Comment by rynk** [comment]
Inpatients are admitted on doctors' orders. An outpatient gets emergency treatment, same-day surgery, lab tests, X-rays or services such as observation without a doctor's written order to admit as an inpatient.

The Wikipedia definition is not accurate because outpatient observation can extend more than 48 hours.  https://www.medicare.gov/what-medicare-covers/part-a/inpatient-or-outpatient.html

Unclear how subgroups are defined; likely they're clusters of Clinical Classification Software codes.
